version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 99
  reviewers: [zunkas, perhassle]
  assignees: [zunkas]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Stockholm
  open-pull-requests-limit: 99
  reviewers: [zunkas, perhassle]
  assignees: [zunkas]